version: '3.4'

services:  
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_HOSTNAME: ${MONGO_INITDB_HOSTNAME}
      MONGO_INITDB_PORT: ${MONGO_INITDB_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}      
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGO_INITDB_PORT}:27017